import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MYTHIC_DIR = resolve(__dirname, '../collections/mythic');
const SVG_PATH = resolve(MYTHIC_DIR, 'mythic.parts.svg');
const TS_PATH = resolve(MYTHIC_DIR, 'mythic-parts.ts');

const svg = readFileSync(SVG_PATH, 'utf-8');

const symbolRe = /<symbol\s+id="([^"]+)"[^>]*>([\s\S]*?)<\/symbol>/g;
const entries: [string, string][] = [];

let match;
while ((match = symbolRe.exec(svg)) !== null) {
  const id = match[1]!;
  const content = match[2]!.trim();
  entries.push([id, content]);
}

entries.sort(([a], [b]) => a.localeCompare(b));

const lines = [
  '// Auto-generated by extract-parts.ts — do not edit manually',
  `// Source: mythic.parts.svg (${entries.length} parts)`,
  '',
  'export const MYTHIC_PARTS = new Map<string, string>([',
];

for (const [id, content] of entries) {
  const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
  lines.push(`  ['${id}', \`${escaped}\`],`);
}

lines.push(']);');
lines.push('');

writeFileSync(TS_PATH, lines.join('\n'), 'utf-8');
console.log(`Extracted ${entries.length} parts to ${TS_PATH}`);
