// AUTO-GENERATED by scripts/generate-schemas.ts — DO NOT EDIT
// Re-generate: yarn workspace @casehubio/blocks-ui-schema run generate
// Source: packages/blocks-ui-schema/src/registry.ts
import { z } from "zod";

export const slaIndicatorPropsSchema = z.object({
  deadline: z.string(),
  slaWindow: z.union([z.null(), z.number()]),
  warningThreshold: z.number(),
  criticalThreshold: z.number(),
  escalationStage: z.union([z.null(), z.string()]),
  compact: z.boolean(),
});

export const executionMonitorPropsSchema = z.object({
  endpoint: z.string().optional(),
  executionId: z.string().optional(),
  data: z.object({
    executionId: z.string(),
    state: z.enum(["IDLE", "RUNNING", "WAITING_FOR_AGENT", "WAITING_FOR_EVENT", "COMPLETE", "FAULTED", "CANCELLED"]),
    model: z.object({
      pattern: z.enum(["SEQUENCE", "PARALLEL", "LOOP", "CONDITIONAL", "SUPERVISOR", "DEBATE", "VOTING", "HTN"]),
      routingStrategy: z.string().optional(),
      decompositionStrategy: z.string().optional(),
      activationStrategy: z.string().optional(),
      aggregationStrategy: z.string().optional(),
      terminationStrategy: z.string().optional(),
      failurePolicy: z.object({
        routingFailureAction: z.enum(["FAIL", "RETRY_BROADER", "ESCALATE"]),
        aggregationFailureAction: z.enum(["FAIL", "ESCALATE", "RETRY_DIFFERENT"]),
        agentRetryPolicy: z.object({
          maxRetries: z.number(),
          backoffStrategy: z.enum(["FIXED", "LINEAR", "EXPONENTIAL"]),
          initialDelayMs: z.number().optional(),
        }).optional(),
      }),
    }),
    result: z.enum(["CANCELLED", "COMPLETED", "FAILED", "ESCALATED"]).optional(),
    activeAgents: z.array(z.object({
        id: z.string(),
        type: z.enum(["WORKER", "CHANNEL", "HUMAN", "EXTERNAL", "COMPOSED"]),
        name: z.string().optional(),
      })),
    completedAgents: z.array(z.object({
        agentRef: z.object({
          id: z.string(),
          type: z.enum(["WORKER", "CHANNEL", "HUMAN", "EXTERNAL", "COMPOSED"]),
          name: z.string().optional(),
        }),
        status: z.enum(["SUCCESS", "FAILURE", "TIMEOUT", "DECLINED"]),
        detail: z.string().optional(),
        error: z.string().optional(),
        duration: z.number().optional(),
      })),
    iteration: z.number().optional(),
    startedAt: z.string().optional(),
    completedAt: z.string().optional(),
  }).optional(),
  selectionTopic: z.string().optional(),
  staleThresholdMs: z.number(),
});

export const kpiMetricRowPropsSchema = z.object({
  metrics: z.array(z.object({
      key: z.string(),
      value: z.union([z.string(), z.number()]),
      label: z.string(),
      unit: z.string().optional(),
      trend: z.object({
        direction: z.enum(["up", "down", "stable"]),
        delta: z.string(),
      }).optional(),
      sparkline: z.array(z.number()).optional(),
      status: z.enum(["normal", "warning", "critical"]).optional(),
    })),
  endpoint: z.union([z.null(), z.string()]),
  columns: z.union([z.null(), z.number()]),
  density: z.enum(["comfortable", "compact", "dense"]),
  refreshInterval: z.union([z.null(), z.number()]),
});

export const approvalGatePropsSchema = z.object({
  gateId: z.string(),
  endpoint: z.string(),
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }),
  prompt: z.string(),
  contextText: z.string(),
  outcomes: z.array(z.object({
      key: z.string(),
      label: z.string(),
      variant: z.enum(["success", "danger", "neutral"]),
    })),
  quorum: z.union([z.null(), z.object({
      required: z.number(),
      total: z.number(),
      voters: z.array(z.object({
          id: z.string(),
          name: z.string(),
          status: z.enum(["voted", "pending"]),
          outcome: z.string().optional(),
        })),
    })]),
  deadline: z.union([z.null(), z.string()]),
  slaWindow: z.union([z.null(), z.number()]),
  history: z.array(z.object({
      timestamp: z.string(),
      actor: z.string(),
      outcome: z.string(),
    })),
  data: z.union([z.null(), z.record(z.unknown())]),
  requireConfirmation: z.boolean(),
});

export const serviceCardPropsSchema = z.object({
  data: z.union([z.null(), z.object({
      serviceName: z.string(),
      serviceId: z.string(),
      image: z.string(),
      replicas: z.number(),
      status: z.string(),
      clusters: z.array(z.object({
          clusterId: z.string(),
          clusterName: z.string(),
          status: z.enum(["converged", "provisioning", "faulted", "unknown"]),
          readyReplicas: z.number(),
          desiredReplicas: z.number(),
        })),
    })]),
  endpoint: z.string().optional(),
});

export const slaBreachPolicyPropsSchema = z.object({
  tiers: z.array(z.object({
      threshold: z.number(),
      label: z.string(),
      consequence: z.string(),
      regulation: z.string().optional(),
    })),
  timeRemaining: z.number(),
  deadline: z.string(),
});

export const trustFeedbackDisplayPropsSchema = z.object({
  gateDecision: z.union([z.null(), z.object({
      decision: z.string(),
      actor: z.string(),
      attestation: z.string(),
      trustScoreBefore: z.number(),
      trustScoreAfter: z.number(),
      dimension: z.string(),
    })]),
  compact: z.boolean(),
});

export const similarityPanelPropsSchema = z.object({
  ariaLabel: z.union([z.null(), z.string()]),
  data: z.union([z.null(), z.array(z.object({
        caseId: z.string(),
        similarity: z.number(),
        outcome: z.string(),
        resolutionTime: z.string(),
      }))]),
  emptyMessage: z.string(),
});

export const complianceSummaryPropsSchema = z.object({
  ariaLabel: z.union([z.null(), z.string()]),
  requirements: z.union([z.null(), z.array(z.object({
        regulation: z.string(),
        requirement: z.string(),
        mechanism: z.string(),
        status: z.enum(["MET", "PARTIAL", "GAP", "BREACHED"]),
        evidenceUrl: z.string().optional(),
      }))]),
});

export const gdprErasureActionPropsSchema = z.object({
  endpoint: z.string(),
  subjectLabel: z.string(),
  reasonOptions: z.array(z.string()),
});

export const workItemRowPropsSchema = z.object({
  item: z.object({
    id: z.string(),
    title: z.string(),
    description: z.union([z.null(), z.string()]),
    types: z.array(z.string()),
    category: z.union([z.null(), z.string()]),
    formKey: z.union([z.null(), z.string()]),
    status: z.enum(["FAULTED", "CANCELLED", "COMPLETED", "ESCALATED", "PENDING", "ASSIGNED", "IN_PROGRESS", "REJECTED", "DELEGATED", "SUSPENDED", "EXPIRED", "OBSOLETE"]),
    priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]),
    assigneeId: z.union([z.null(), z.string()]),
    owner: z.union([z.null(), z.string()]),
    candidateGroups: z.union([z.null(), z.string()]),
    candidateUsers: z.union([z.null(), z.string()]),
    requiredCapabilities: z.union([z.null(), z.string()]),
    createdBy: z.union([z.null(), z.string()]),
    delegationDeclineTarget: z.union([z.null(), z.string(), z.string()]),
    delegationChain: z.union([z.null(), z.string()]),
    priorStatus: z.union([z.null(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string()]),
    payload: z.union([z.null(), z.string()]),
    resolution: z.union([z.null(), z.string()]),
    claimDeadline: z.union([z.null(), z.string()]),
    expiresAt: z.union([z.null(), z.string()]),
    followUpDate: z.union([z.null(), z.string()]),
    createdAt: z.string(),
    updatedAt: z.string(),
    assignedAt: z.union([z.null(), z.string()]),
    startedAt: z.union([z.null(), z.string()]),
    completedAt: z.union([z.null(), z.string()]),
    suspendedAt: z.union([z.null(), z.string()]),
    labels: z.array(z.object({
        name: z.string(),
        value: z.union([z.null(), z.string()]),
      })),
    confidenceScore: z.union([z.null(), z.number()]),
    callerRef: z.union([z.null(), z.string()]),
    version: z.number(),
    templateId: z.union([z.null(), z.string()]),
    outcome: z.union([z.null(), z.string()]),
    permittedOutcomes: z.union([z.null(), z.array(z.object({
          value: z.string(),
          label: z.string(),
        }))]),
    inputDataSchema: z.union([z.null(), z.string()]),
    outputDataSchema: z.union([z.null(), z.string()]),
    excludedUsers: z.union([z.null(), z.string()]),
    scope: z.union([z.null(), z.string()]),
    percentComplete: z.union([z.null(), z.number()]),
    statusNote: z.union([z.null(), z.string()]),
  }),
});

export const dimensionDashboardPropsSchema = z.object({
  data: z.union([z.null(), z.object({
      serviceId: z.string(),
      serviceName: z.string(),
      overallHealth: z.string(),
      dimensions: z.array(z.object({
          type: z.string(),
          label: z.string(),
          status: z.string(),
          severity: z.enum(["LOW", "MEDIUM", "HIGH", "OK", "CRITICAL"]),
          activeResponses: z.number(),
          lastUpdated: z.string().optional(),
        })),
    })]),
  endpoint: z.string().optional(),
  compact: z.boolean(),
});

export const routingRationalePropsSchema = z.object({
  data: z.union([z.null(), z.object({
      capabilityTag: z.string(),
      strategyId: z.string(),
      selected: z.object({
        workerId: z.string(),
        trustScore: z.union([z.null(), z.number()]),
        workloadScore: z.number(),
        phase: z.enum(["BOOTSTRAP", "QUALIFIED", "BORDERLINE", "EXCLUDED_PHASE2B", "EXCLUDED_PHASE3"]),
        observations: z.number(),
        finalScore: z.number(),
        exclusionReason: z.string().optional(),
        rationale: z.string().optional(),
        additionalScores: z.record(z.number()).optional(),
      }),
      alternatives: z.array(z.object({
          workerId: z.string(),
          trustScore: z.union([z.null(), z.number()]),
          workloadScore: z.number(),
          phase: z.enum(["BOOTSTRAP", "QUALIFIED", "BORDERLINE", "EXCLUDED_PHASE2B", "EXCLUDED_PHASE3"]),
          observations: z.number(),
          finalScore: z.number(),
          exclusionReason: z.string().optional(),
          rationale: z.string().optional(),
          additionalScores: z.record(z.number()).optional(),
        })),
      policy: z.object({
        threshold: z.number(),
        borderlineMargin: z.number(),
        blendFactor: z.number(),
        minimumObservations: z.number(),
        qualityFloors: z.record(z.number()),
        cbrWeight: z.number(),
        bootstrapEscalationRequired: z.boolean(),
      }),
    })]),
  scoreLabel: z.string(),
  capabilityLabel: z.string().optional(),
});

export const trustScorePanelPropsSchema = z.object({
  actorId: z.string().optional(),
  mode: z.enum(["compact", "full"]),
  score: z.number().optional(),
  trustLevel: z.enum(["high", "adequate", "low", "none"]).optional(),
});

export const groupedDataViewPropsSchema = z.object({
  ariaLabel: z.union([z.null(), z.string()]),
  groupBy: z.string(),
  groupOrder: z.array(z.string()).optional(),
  preset: z.enum(["sectioned", "spreadsheet", "list"]),
  defaultExpanded: z.boolean(),
  sortable: z.boolean(),
});

export const auditTrailViewerPropsSchema = z.object({
  endpoint: z.string().optional(),
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }).optional(),
  subjectId: z.string().optional(),
  actorId: z.string().optional(),
});

export const listPanePropsSchema = z.object({
  selectionTopic: z.string(),
  emptyMessage: z.string(),
  pageSize: z.number(),
});

export const detailPanePropsSchema = z.object({
  tabs: z.array(z.object({
      id: z.string(),
      label: z.string(),
      tagName: z.string(),
      icon: z.string().optional(),
      order: z.number().optional(),
    })),
  selectionTopic: z.string(),
  emptyMessage: z.string(),
});

export const workItemInboxPropsSchema = z.object({
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }),
  endpoint: z.string().optional(),
  data: z.array(z.object({
      item: z.object({
        id: z.string(),
        title: z.string(),
        description: z.union([z.null(), z.string()]),
        types: z.array(z.string()),
        category: z.union([z.null(), z.string()]),
        formKey: z.union([z.null(), z.string()]),
        status: z.enum(["FAULTED", "CANCELLED", "COMPLETED", "ESCALATED", "PENDING", "ASSIGNED", "IN_PROGRESS", "REJECTED", "DELEGATED", "SUSPENDED", "EXPIRED", "OBSOLETE"]),
        priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]),
        assigneeId: z.union([z.null(), z.string()]),
        owner: z.union([z.null(), z.string()]),
        candidateGroups: z.union([z.null(), z.string()]),
        candidateUsers: z.union([z.null(), z.string()]),
        requiredCapabilities: z.union([z.null(), z.string()]),
        createdBy: z.union([z.null(), z.string()]),
        delegationDeclineTarget: z.union([z.null(), z.string(), z.string()]),
        delegationChain: z.union([z.null(), z.string()]),
        priorStatus: z.union([z.null(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string()]),
        payload: z.union([z.null(), z.string()]),
        resolution: z.union([z.null(), z.string()]),
        claimDeadline: z.union([z.null(), z.string()]),
        expiresAt: z.union([z.null(), z.string()]),
        followUpDate: z.union([z.null(), z.string()]),
        createdAt: z.string(),
        updatedAt: z.string(),
        assignedAt: z.union([z.null(), z.string()]),
        startedAt: z.union([z.null(), z.string()]),
        completedAt: z.union([z.null(), z.string()]),
        suspendedAt: z.union([z.null(), z.string()]),
        labels: z.array(z.object({
            name: z.string(),
            value: z.union([z.null(), z.string()]),
          })),
        confidenceScore: z.union([z.null(), z.number()]),
        callerRef: z.union([z.null(), z.string()]),
        version: z.number(),
        templateId: z.union([z.null(), z.string()]),
        outcome: z.union([z.null(), z.string()]),
        permittedOutcomes: z.union([z.null(), z.array(z.object({
              value: z.string(),
              label: z.string(),
            }))]),
        inputDataSchema: z.union([z.null(), z.string()]),
        outputDataSchema: z.union([z.null(), z.string()]),
        excludedUsers: z.union([z.null(), z.string()]),
        scope: z.union([z.null(), z.string()]),
        percentComplete: z.union([z.null(), z.number()]),
        statusNote: z.union([z.null(), z.string()]),
      }),
      childCount: z.number(),
      completedCount: z.union([z.null(), z.number()]),
      requiredCount: z.union([z.null(), z.number()]),
      groupStatus: z.union([z.null(), z.string()]),
    })).optional(),
  mode: z.enum(["my-work", "claimable", "all"]),
});

export const workItemDetailPropsSchema = z.object({
  endpoint: z.union([z.null(), z.string()]),
  workItemId: z.union([z.null(), z.string()]),
  identity: z.union([z.null(), z.object({
      userId: z.string(),
      displayName: z.string(),
      groups: z.array(z.string()),
      tenancyId: z.string().optional(),
    })]),
  data: z.union([z.null(), z.object({
      id: z.string(),
      title: z.string(),
      description: z.union([z.null(), z.string()]),
      types: z.array(z.string()),
      category: z.union([z.null(), z.string()]),
      formKey: z.union([z.null(), z.string()]),
      status: z.enum(["FAULTED", "CANCELLED", "COMPLETED", "ESCALATED", "PENDING", "ASSIGNED", "IN_PROGRESS", "REJECTED", "DELEGATED", "SUSPENDED", "EXPIRED", "OBSOLETE"]),
      priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]),
      assigneeId: z.union([z.null(), z.string()]),
      owner: z.union([z.null(), z.string()]),
      candidateGroups: z.union([z.null(), z.string()]),
      candidateUsers: z.union([z.null(), z.string()]),
      requiredCapabilities: z.union([z.null(), z.string()]),
      createdBy: z.union([z.null(), z.string()]),
      delegationDeclineTarget: z.union([z.null(), z.string(), z.string()]),
      delegationChain: z.union([z.null(), z.string()]),
      priorStatus: z.union([z.null(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string(), z.string()]),
      payload: z.union([z.null(), z.string()]),
      resolution: z.union([z.null(), z.string()]),
      claimDeadline: z.union([z.null(), z.string()]),
      expiresAt: z.union([z.null(), z.string()]),
      followUpDate: z.union([z.null(), z.string()]),
      createdAt: z.string(),
      updatedAt: z.string(),
      assignedAt: z.union([z.null(), z.string()]),
      startedAt: z.union([z.null(), z.string()]),
      completedAt: z.union([z.null(), z.string()]),
      suspendedAt: z.union([z.null(), z.string()]),
      labels: z.array(z.object({
          name: z.string(),
          value: z.union([z.null(), z.string()]),
        })),
      confidenceScore: z.union([z.null(), z.number()]),
      callerRef: z.union([z.null(), z.string()]),
      version: z.number(),
      templateId: z.union([z.null(), z.string()]),
      outcome: z.union([z.null(), z.string()]),
      permittedOutcomes: z.union([z.null(), z.array(z.object({
            value: z.string(),
            label: z.string(),
          }))]),
      inputDataSchema: z.union([z.null(), z.string()]),
      outputDataSchema: z.union([z.null(), z.string()]),
      excludedUsers: z.union([z.null(), z.string()]),
      scope: z.union([z.null(), z.string()]),
      percentComplete: z.union([z.null(), z.number()]),
      statusNote: z.union([z.null(), z.string()]),
    })]),
});

export const workItemWorkbenchPropsSchema = z.object({
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }),
  endpoint: z.string(),
});

export const workerTaskPanePropsSchema = z.object({
  layout: z.enum(["split", "stacked"]),
  endpoint: z.string(),
  selectionTopic: z.string(),
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }),
  respondEndpoint: z.string(),
  declineReasons: z.array(z.string()),
  claimEndpoint: z.string(),
  eventStreamEndpoint: z.string(),
  showContext: z.boolean(),
  showWorkspace: z.boolean(),
});

export const notificationInboxPropsSchema = z.object({
  endpoint: z.string().optional(),
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }).optional(),
});

export const notificationBellPropsSchema = z.object({
  endpoint: z.string().optional(),
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }).optional(),
  open: z.boolean(),
});

export const subscriptionEditorPropsSchema = z.object({
  endpoint: z.string().optional(),
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }).optional(),
});

export const notificationPreferencesPropsSchema = z.object({
  endpoint: z.string().optional(),
  identity: z.object({
    userId: z.string(),
    displayName: z.string(),
    groups: z.array(z.string()),
    tenancyId: z.string().optional(),
  }).optional(),
});

export const channelActivityPropsSchema = z.object({
  selectionTopic: z.string(),
  channelNavLayout: z.enum(["sidebar", "dropdown"]),
  sidebarOpen: z.boolean(),
  currentActorId: z.string().optional(),
  autoScroll: z.boolean(),
  staleCursorMinutes: z.number(),
  terminalDimming: z.boolean(),
  eventStyling: z.boolean(),
  viewMode: z.enum(["flat", "threaded", "topics"]),
  selectedMessageId: z.string().optional(),
  showTypeSelector: z.boolean(),
  showTopicSelector: z.boolean(),
  showCreate: z.boolean(),
  showDelete: z.boolean(),
});

export const convergenceIndicatorPropsSchema = z.object({
  signal: z.object({
    state: z.enum(["PROGRESSING", "CONVERGING", "CONSENSUS", "DEADLOCK", "DIMINISHING_RETURNS"]),
    confidence: z.number(),
    reason: z.string(),
  }).optional(),
  size: z.enum(["sm", "md"]),
});

export const commonGroundPanelPropsSchema = z.object({
  commonGround: z.object({
    facts: z.array(z.object({
        id: z.string(),
        topic: z.string(),
        content: z.string(),
        epistemicStatus: z.enum(["PENDING", "ESTABLISHED", "DISPUTED"]),
        acknowledgedBy: z.array(z.string()),
        disputedBy: z.array(z.string()),
        round: z.number(),
      })),
  }).optional(),
  factTopic: z.string(),
});

export const conversationWorkbenchPropsSchema = z.object({
  conversationState: z.object({
    points: z.array(z.object({
        id: z.string(),
        topic: z.string(),
        round: z.number(),
        classification: z.object({
          priority: z.string(),
          scope: z.string(),
          location: z.string().optional(),
        }),
        entries: z.array(z.object({
            entryType: z.string(),
            content: z.string(),
            agentRole: z.string(),
            round: z.number(),
            timestamp: z.string().optional(),
          })),
        status: z.string(),
        convergenceSignal: z.object({
          state: z.enum(["PROGRESSING", "CONVERGING", "CONSENSUS", "DEADLOCK", "DIMINISHING_RETURNS"]),
          confidence: z.number(),
          reason: z.string(),
        }).optional(),
      })),
    convergence: z.object({
      state: z.enum(["PROGRESSING", "CONVERGING", "CONSENSUS", "DEADLOCK", "DIMINISHING_RETURNS"]),
      confidence: z.number(),
      reason: z.string(),
    }),
    commonGround: z.object({
      facts: z.array(z.object({
          id: z.string(),
          topic: z.string(),
          content: z.string(),
          epistemicStatus: z.enum(["PENDING", "ESTABLISHED", "DISPUTED"]),
          acknowledgedBy: z.array(z.string()),
          disputedBy: z.array(z.string()),
          round: z.number(),
        })),
    }),
    humanFlags: z.array(z.object({
        id: z.string(),
        pointId: z.string(),
        content: z.string(),
        flaggedBy: z.string(),
        round: z.number(),
      })),
    memos: z.array(z.object({
        agentRole: z.string(),
        content: z.string(),
        round: z.number(),
      })),
    subTaskFindings: z.array(z.object({
        id: z.string(),
        pointId: z.string(),
        taskType: z.string(),
        content: z.string(),
        status: z.string(),
        round: z.number(),
      })),
    obligations: z.array(z.object({
        pointId: z.string(),
        correlationId: z.string(),
        commitment: z.object({
          state: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]),
          deadline: z.string().optional(),
          acknowledgedAt: z.string().optional(),
          resolvedAt: z.string().optional(),
          createdAt: z.string(),
          updatedAt: z.string(),
        }),
        transitions: z.array(z.object({
            from: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]),
            to: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]),
            actor: z.string().optional(),
            timestamp: z.string(),
          })),
      })),
    currentRound: z.number(),
  }).optional(),
  selectionTopic: z.string(),
  factTopic: z.string(),
});

export const pointListPropsSchema = z.object({
  points: z.array(z.object({
      id: z.string(),
      topic: z.string(),
      round: z.number(),
      classification: z.object({
        priority: z.string(),
        scope: z.string(),
        location: z.string().optional(),
      }),
      entries: z.array(z.object({
          entryType: z.string(),
          content: z.string(),
          agentRole: z.string(),
          round: z.number(),
          timestamp: z.string().optional(),
        })),
      status: z.string(),
      convergenceSignal: z.object({
        state: z.enum(["PROGRESSING", "CONVERGING", "CONSENSUS", "DEADLOCK", "DIMINISHING_RETURNS"]),
        confidence: z.number(),
        reason: z.string(),
      }).optional(),
    })),
  currentRound: z.number(),
  selectionTopic: z.string(),
});

export const pointDetailPropsSchema = z.object({
  point: z.object({
    id: z.string(),
    topic: z.string(),
    round: z.number(),
    classification: z.object({
      priority: z.string(),
      scope: z.string(),
      location: z.string().optional(),
    }),
    entries: z.array(z.object({
        entryType: z.string(),
        content: z.string(),
        agentRole: z.string(),
        round: z.number(),
        timestamp: z.string().optional(),
      })),
    status: z.string(),
    convergenceSignal: z.object({
      state: z.enum(["PROGRESSING", "CONVERGING", "CONSENSUS", "DEADLOCK", "DIMINISHING_RETURNS"]),
      confidence: z.number(),
      reason: z.string(),
    }).optional(),
  }).optional(),
  findings: z.array(z.object({
      id: z.string(),
      pointId: z.string(),
      taskType: z.string(),
      content: z.string(),
      status: z.string(),
      round: z.number(),
    })),
  flags: z.array(z.object({
      id: z.string(),
      pointId: z.string(),
      content: z.string(),
      flaggedBy: z.string(),
      round: z.number(),
    })),
  obligations: z.array(z.object({
      pointId: z.string(),
      correlationId: z.string(),
      commitment: z.object({
        state: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]),
        deadline: z.string().optional(),
        acknowledgedAt: z.string().optional(),
        resolvedAt: z.string().optional(),
        createdAt: z.string(),
        updatedAt: z.string(),
      }),
      transitions: z.array(z.object({
          from: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]),
          to: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]),
          actor: z.string().optional(),
          timestamp: z.string(),
        })),
    })),
});

export const caseExplorerPropsSchema = z.object({
  entityTypes: z.array(z.object({
      type: z.string(),
      label: z.string(),
      icon: z.string().optional(),
      listEndpoint: z.string(),
      columnConfig: z.array(z.unknown()),
      columnRenderers: z.record(z.object({})).optional(),
      detailRendererMap: z.record(z.union([z.string(), z.object({})])).optional(),
      relationships: z.array(z.object({
          childType: z.string(),
          label: z.string(),
          endpointTemplate: z.string(),
        })).optional(),
      filters: z.array(z.object({
          field: z.string(),
          label: z.string(),
          type: z.enum(["text", "select", "date-range", "status"]),
          options: z.array(z.object({
              value: z.string(),
              label: z.string(),
            })).optional(),
        })).optional(),
      subTypes: z.array(z.string()).optional(),
      eventTopics: z.array(z.string()).optional(),
      reader: z.object({}).optional(),
      responseReader: z.object({}).optional(),
    })),
});

export const entityListPropsSchema = z.object({
  endpoint: z.string(),
  selectionTopic: z.string(),
  pageSize: z.number(),
});

export const entityDetailPropsSchema = z.object({
  selectionTopic: z.string(),
});

export const entityTreePropsSchema = z.object({
  selectionTopic: z.string(),
});

export const orchestrationWorkbenchPropsSchema = z.object({
  endpoint: z.string(),
  executionId: z.string().optional(),
  selectionTopic: z.string(),
});

export const dagViewerPropsSchema = z.object({
  dagPlan: z.union([z.null(), z.object({
      nodes: z.record(z.object({
          id: z.string(),
          taskId: z.string(),
          taskDescription: z.string().optional(),
          executorName: z.string().optional(),
          dependsOn: z.array(z.string()),
          joinType: z.enum(["ALL_OF", "ANY_OF"]),
        })),
      timestamp: z.string(),
    })]),
  dagResult: z.union([z.null(), z.object({
      nodeStates: z.record(z.object({
          kind: z.enum(["Pending", "Dispatched", "Completed", "Failed", "Skipped", "Cancelled"]),
          reason: z.string().optional(),
        })),
      completedResults: z.record(z.unknown()).optional(),
      allSucceeded: z.boolean(),
      elapsed: z.string(),
      timestamp: z.string(),
    })]),
  dispatchMode: z.union([z.null(), z.string(), z.string()]),
  selectionTopic: z.string(),
});

export const decompositionTreePropsSchema = z.object({
  decomposition: z.union([z.null(), z.object({
      root: z.union([z.object({
          kind: z.string(),
          id: z.string(),
          description: z.string().optional(),
          executorName: z.string().optional(),
        }), z.object({
          kind: z.string(),
          id: z.string(),
          name: z.string(),
          methods: z.array(z.object({
              guardLabel: z.string().optional(),
              strategyId: z.string(),
              children: z.array(z.unknown()),
            })),
        })]),
      timestamp: z.string(),
    })]),
  selectionTopic: z.string(),
});

export const planItemTreePropsSchema = z.object({
  definition: z.union([z.null(), z.object({
      kind: z.string(),
      id: z.string(),
      name: z.string(),
      executor: z.object({
        name: z.string(),
        description: z.string().optional(),
      }),
      entryCondition: z.string().optional(),
    }), z.object({
      kind: z.string(),
      id: z.string(),
      name: z.string(),
      children: z.array(z.union([z.object({
            kind: z.string(),
            id: z.string(),
            name: z.string(),
            executor: z.object({
              name: z.string(),
              description: z.string().optional(),
            }),
            entryCondition: z.string().optional(),
          }), z.object({
            kind: z.string(),
            id: z.string(),
            name: z.string(),
            children: z.array(z.union([z.unknown(), z.unknown()])),
            planningStrategy: z.string().optional(),
            completion: z.union([z.object({
                kind: z.unknown(),
              }), z.object({
                kind: z.unknown(),
                m: z.unknown(),
              }), z.object({
                kind: z.unknown(),
              })]),
            dispatchMode: z.enum(["ORCHESTRATED", "CHOREOGRAPHED"]),
            entryCondition: z.string().optional(),
            exitCondition: z.string().optional(),
            repeatable: z.boolean(),
            scopedBindings: z.record(z.enum(["PARTICIPANT", "COMPANION"])).optional(),
          })])),
      planningStrategy: z.string().optional(),
      completion: z.union([z.object({
          kind: z.string(),
        }), z.object({
          kind: z.string(),
          m: z.number(),
        }), z.object({
          kind: z.string(),
        })]),
      dispatchMode: z.enum(["ORCHESTRATED", "CHOREOGRAPHED"]),
      entryCondition: z.string().optional(),
      exitCondition: z.string().optional(),
      repeatable: z.boolean(),
      scopedBindings: z.record(z.enum(["PARTICIPANT", "COMPANION"])).optional(),
    })]),
});

export const planModelDashboardPropsSchema = z.object({
  planModel: z.union([z.null(), z.object({
      caseId: z.string(),
      agenda: z.array(z.object({
          planItemId: z.string(),
          bindingName: z.string(),
          status: z.string(),
          description: z.string().optional(),
        })),
      focus: z.string().optional(),
      focusRationale: z.string().optional(),
      resourceBudget: z.record(z.unknown()),
      subCases: z.array(z.object({
          caseDefinition: z.string(),
          namespace: z.string(),
          status: z.string().optional(),
        })),
      compounds: z.array(z.object({
          id: z.string(),
          name: z.string(),
          status: z.string(),
          childCount: z.number(),
          completedCount: z.number(),
          completion: z.union([z.object({
              kind: z.string(),
            }), z.object({
              kind: z.string(),
              m: z.number(),
            }), z.object({
              kind: z.string(),
            })]),
        })),
      timestamp: z.string(),
    })]),
});

export const caseFlowViewerPropsSchema = z.object({
  runtimeState: z.union([z.null(), z.object({
      planItems: z.array(z.object({
          id: z.string(),
          bindingName: z.string(),
          status: z.enum(["RUNNING", "FAULTED", "CANCELLED", "COMPLETED", "PENDING", "REJECTED", "DELEGATED", "SUSPENDED", "OBSOLETE"]),
          createdAt: z.string(),
        })),
      milestones: z.array(z.object({
          name: z.string(),
          status: z.enum(["COMPLETED", "PENDING", "ACTIVE"]),
        })),
      timestamp: z.string(),
      caseStatus: z.string().optional(),
      trustScores: z.array(z.object({
          bindingName: z.string(),
          workerId: z.string(),
          score: z.number(),
        })).optional(),
      adaptiveDecisions: z.array(z.object({
          trigger: z.string(),
          condition: z.string(),
          fired: z.boolean(),
          timestamp: z.string(),
          affectedBindings: z.array(z.string()).optional(),
        })).optional(),
      parallelGroups: z.array(z.array(z.string())).optional(),
    })]),
  selectionTopic: z.string(),
});

export const caseDependencyGraphPropsSchema = z.object({
  endpoint: z.string().optional(),
  selectionTopic: z.string(),
});

export const diagramWorkbenchPropsSchema = z.object({
  yaml: z.string(),
  src: z.string(),
  runtimeState: z.union([z.null(), z.object({
      planItems: z.array(z.object({
          id: z.string(),
          bindingName: z.string(),
          status: z.enum(["RUNNING", "FAULTED", "CANCELLED", "COMPLETED", "PENDING", "REJECTED", "DELEGATED", "SUSPENDED", "OBSOLETE"]),
          createdAt: z.string(),
        })),
      milestones: z.array(z.object({
          name: z.string(),
          status: z.enum(["COMPLETED", "PENDING", "ACTIVE"]),
        })),
      timestamp: z.string(),
      caseStatus: z.string().optional(),
      trustScores: z.array(z.object({
          bindingName: z.string(),
          workerId: z.string(),
          score: z.number(),
        })).optional(),
      adaptiveDecisions: z.array(z.object({
          trigger: z.string(),
          condition: z.string(),
          fired: z.boolean(),
          timestamp: z.string(),
          affectedBindings: z.array(z.string()).optional(),
        })).optional(),
      parallelGroups: z.array(z.array(z.string())).optional(),
    })]),
});

export const clusterPanelPropsSchema = z.object({
  data: z.union([z.null(), z.array(z.object({
        id: z.string(),
        name: z.string(),
        apiUrl: z.string(),
        namespace: z.string(),
        type: z.enum(["KUBERNETES", "OPENSHIFT"]),
        status: z.enum(["CONNECTED", "UNREACHABLE", "UNKNOWN"]),
        applicationCount: z.number(),
      }))]),
  endpoint: z.string().optional(),
  readonly: z.boolean(),
});

export const reconciliationStatusPropsSchema = z.object({
  data: z.union([z.null(), z.object({
      clusters: z.array(z.object({
          clusterId: z.string(),
          clusterName: z.string(),
          nodeCount: z.number(),
          convergedCount: z.number(),
          driftedCount: z.number(),
          faultedCount: z.number(),
          nodes: z.array(z.object({
              nodeId: z.string(),
              nodeType: z.string(),
              desired: z.string(),
              actual: z.string(),
              status: z.enum(["FAULTED", "CONVERGED", "DRIFTED", "PROVISIONING", "ABSENT"]),
            })),
        })),
      lastReconciled: z.string().optional(),
    })]),
  endpoint: z.string().optional(),
});

export const topologyViewerPropsSchema = z.object({
  data: z.union([z.null(), z.object({
      services: z.array(z.object({
          id: z.string(),
          name: z.string(),
          status: z.enum(["RUNNING", "FAULTED", "ABSENT", "DEGRADED", "DEPLOYING"]),
          replicas: z.number().optional(),
          image: z.string().optional(),
          type: z.string().optional(),
        })),
      edges: z.array(z.object({
          source: z.string(),
          target: z.string(),
          label: z.string().optional(),
        })),
    })]),
  endpoint: z.string().optional(),
  selectionTopic: z.string(),
});

export const sessionListPropsSchema = z.object({
  endpoint: z.string(),
});

export const sessionDetailPropsSchema = z.object({
  endpoint: z.string(),
  sessionId: z.string().optional(),
  eventsPushUrl: z.string(),
});

export const sessionWorkbenchPropsSchema = z.object({
  endpoint: z.string(),
});

export const preferencesEditorPropsSchema = z.object({
  endpoint: z.string(),
});

export const trustWorkbenchPropsSchema = z.object({
  endpoint: z.string(),
  actorId: z.string(),
});

export const contributorWorkbenchPropsSchema = z.object({
  endpoint: z.string(),
  actorId: z.string(),
});

export const commitmentRangeBarPropsSchema = z.object({
  state: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]).optional(),
  createdAt: z.string().optional(),
  resolvedAt: z.string().optional(),
  acknowledgedAt: z.string().optional(),
  deadline: z.string().optional(),
  mode: z.enum(["compact", "detailed"]),
});

export const commitmentTransitionBadgePropsSchema = z.object({
  transition: z.object({
    from: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]),
    to: z.enum(["FAILED", "DECLINED", "DELEGATED", "EXPIRED", "OPEN", "ACKNOWLEDGED", "FULFILLED"]),
    actor: z.string().optional(),
    timestamp: z.string(),
  }).optional(),
  compact: z.boolean(),
});

export const blocksComponentSchemaMap: ReadonlyMap<string, z.ZodType> = new Map([
  ["blocks-sla-indicator", slaIndicatorPropsSchema] as [string, z.ZodType],
  ["blocks-execution-monitor", executionMonitorPropsSchema] as [string, z.ZodType],
  ["blocks-kpi-metric-row", kpiMetricRowPropsSchema] as [string, z.ZodType],
  ["blocks-approval-gate", approvalGatePropsSchema] as [string, z.ZodType],
  ["blocks-service-card", serviceCardPropsSchema] as [string, z.ZodType],
  ["blocks-sla-breach-policy", slaBreachPolicyPropsSchema] as [string, z.ZodType],
  ["blocks-trust-feedback-display", trustFeedbackDisplayPropsSchema] as [string, z.ZodType],
  ["blocks-similarity-panel", similarityPanelPropsSchema] as [string, z.ZodType],
  ["blocks-compliance-summary", complianceSummaryPropsSchema] as [string, z.ZodType],
  ["blocks-gdpr-erasure-action", gdprErasureActionPropsSchema] as [string, z.ZodType],
  ["blocks-work-item-row", workItemRowPropsSchema] as [string, z.ZodType],
  ["blocks-dimension-dashboard", dimensionDashboardPropsSchema] as [string, z.ZodType],
  ["blocks-routing-rationale", routingRationalePropsSchema] as [string, z.ZodType],
  ["blocks-trust-score-panel", trustScorePanelPropsSchema] as [string, z.ZodType],
  ["blocks-grouped-data-view", groupedDataViewPropsSchema] as [string, z.ZodType],
  ["blocks-audit-trail-viewer", auditTrailViewerPropsSchema] as [string, z.ZodType],
  ["blocks-list-pane", listPanePropsSchema] as [string, z.ZodType],
  ["blocks-detail-pane", detailPanePropsSchema] as [string, z.ZodType],
  ["blocks-work-item-inbox", workItemInboxPropsSchema] as [string, z.ZodType],
  ["blocks-work-item-detail", workItemDetailPropsSchema] as [string, z.ZodType],
  ["blocks-work-item-workbench", workItemWorkbenchPropsSchema] as [string, z.ZodType],
  ["blocks-worker-task-pane", workerTaskPanePropsSchema] as [string, z.ZodType],
  ["blocks-notification-inbox", notificationInboxPropsSchema] as [string, z.ZodType],
  ["blocks-notification-bell", notificationBellPropsSchema] as [string, z.ZodType],
  ["blocks-subscription-editor", subscriptionEditorPropsSchema] as [string, z.ZodType],
  ["blocks-notification-preferences", notificationPreferencesPropsSchema] as [string, z.ZodType],
  ["blocks-channel-activity", channelActivityPropsSchema] as [string, z.ZodType],
  ["blocks-convergence-indicator", convergenceIndicatorPropsSchema] as [string, z.ZodType],
  ["blocks-common-ground-panel", commonGroundPanelPropsSchema] as [string, z.ZodType],
  ["blocks-conversation-workbench", conversationWorkbenchPropsSchema] as [string, z.ZodType],
  ["blocks-point-list", pointListPropsSchema] as [string, z.ZodType],
  ["blocks-point-detail", pointDetailPropsSchema] as [string, z.ZodType],
  ["blocks-case-explorer", caseExplorerPropsSchema] as [string, z.ZodType],
  ["blocks-entity-list", entityListPropsSchema] as [string, z.ZodType],
  ["blocks-entity-detail", entityDetailPropsSchema] as [string, z.ZodType],
  ["blocks-entity-tree", entityTreePropsSchema] as [string, z.ZodType],
  ["blocks-orchestration-workbench", orchestrationWorkbenchPropsSchema] as [string, z.ZodType],
  ["blocks-dag-viewer", dagViewerPropsSchema] as [string, z.ZodType],
  ["blocks-decomposition-tree", decompositionTreePropsSchema] as [string, z.ZodType],
  ["blocks-plan-item-tree", planItemTreePropsSchema] as [string, z.ZodType],
  ["blocks-plan-model-dashboard", planModelDashboardPropsSchema] as [string, z.ZodType],
  ["blocks-case-flow-viewer", caseFlowViewerPropsSchema] as [string, z.ZodType],
  ["blocks-case-dependency-graph", caseDependencyGraphPropsSchema] as [string, z.ZodType],
  ["blocks-diagram-workbench", diagramWorkbenchPropsSchema] as [string, z.ZodType],
  ["blocks-cluster-panel", clusterPanelPropsSchema] as [string, z.ZodType],
  ["blocks-reconciliation-status", reconciliationStatusPropsSchema] as [string, z.ZodType],
  ["blocks-topology-viewer", topologyViewerPropsSchema] as [string, z.ZodType],
  ["blocks-session-list", sessionListPropsSchema] as [string, z.ZodType],
  ["blocks-session-detail", sessionDetailPropsSchema] as [string, z.ZodType],
  ["blocks-session-workbench", sessionWorkbenchPropsSchema] as [string, z.ZodType],
  ["blocks-preferences-editor", preferencesEditorPropsSchema] as [string, z.ZodType],
  ["blocks-trust-workbench", trustWorkbenchPropsSchema] as [string, z.ZodType],
  ["blocks-contributor-workbench", contributorWorkbenchPropsSchema] as [string, z.ZodType],
  ["commitment-range-bar", commitmentRangeBarPropsSchema] as [string, z.ZodType],
  ["commitment-transition-badge", commitmentTransitionBadgePropsSchema] as [string, z.ZodType],
]);
