// AUTO-GENERATED by scripts/generate-domain-schemas.ts — DO NOT EDIT
// Re-generate: yarn workspace @casehubio/lsp-schemas run generate
// Source: ../../graph-stencil-htn/src/types/htn-yaml.ts
import { z } from "zod";

const htnTaskYamlSchema: z.ZodType<unknown> = z.lazy(() => z.object({
    name: z.string(),
    capability: z.string().optional(),
    definitionRef: z.string().optional(),
    methods: z.array(z.object({
        guard: z.string().optional(),
        guardLabel: z.string().optional(),
        strategy: z.string().optional(),
        estimatedCost: z.number().optional(),
        estimatedDuration: z.string().optional(),
        tasks: z.array(z.lazy(() => htnTaskYamlSchema)),
      })).optional(),
  }));

export const htnDocumentSchema = z.object({
    dsl: z.string().optional(),
    namespace: z.string().optional(),
    name: z.string().optional(),
    spec: z.object({
      decomposition: z.object({
        root: z.object({
          name: z.string(),
          capability: z.string().optional(),
          definitionRef: z.string().optional(),
          methods: z.array(z.object({
              guard: z.string().optional(),
              guardLabel: z.string().optional(),
              strategy: z.string().optional(),
              estimatedCost: z.number().optional(),
              estimatedDuration: z.string().optional(),
              tasks: z.array(z.lazy(() => htnTaskYamlSchema)),
            })).optional(),
        }),
      }),
    }),
  });
