// AUTO-GENERATED by scripts/generate-domain-schemas.ts — DO NOT EDIT
// Re-generate: yarn workspace @casehubio/lsp-schemas run generate
// Source: ../../graph-stencil-org/src/types.ts
import { z } from "zod";

export const orgDocumentSchema = z.object({
    organization: z.object({
      units: z.array(z.object({
          unitId: z.string(),
          name: z.string(),
          kind: z.string().optional(),
          kindVocabulary: z.string().optional(),
          tenancyId: z.string(),
          parentUnitId: z.string().optional(),
          members: z.array(z.object({
              agentId: z.string(),
              role: z.string().optional(),
              roleVocabulary: z.string().optional(),
            })),
          capabilities: z.array(z.object({
              name: z.string(),
              description: z.string().optional(),
            })),
          goals: z.array(z.object({
              name: z.string(),
              description: z.string().optional(),
              priority: z.string().optional(),
              visibility: z.string().optional(),
            })),
          constraints: z.array(z.object({
              name: z.string(),
              description: z.string().optional(),
              severity: z.string().optional(),
              visibility: z.string().optional(),
            })),
        })),
      relationships: z.array(z.object({
          sourceAgentId: z.string(),
          targetAgentId: z.string(),
          kind: z.enum(["SUPERVISES", "DELEGATES_TO", "ESCALATES_TO", "REPORTS_TO", "BACKS_UP", "EXTENDED"]),
          extendedKind: z.string().optional(),
          kindVocabulary: z.string().optional(),
          scope: z.object({
            capabilityName: z.string().optional(),
            domain: z.string().optional(),
            custom: z.string().optional(),
          }).optional(),
          attestation: z.object({
            dimensions: z.array(z.string()),
            capabilityScope: z.array(z.string()).optional(),
            signalTypes: z.array(z.enum(["DECLINE", "SUCCESS", "COMPLIANT", "VIOLATED"])).optional(),
          }).optional(),
          tenancyId: z.string(),
        })),
    }),
  });
