// AUTO-GENERATED by scripts/generate-domain-schemas.ts — DO NOT EDIT
// Re-generate: yarn workspace @casehubio/lsp-schemas run generate
// Source: ../../graph-stencil-swf/src/swf-yaml.ts
import { z } from "zod";

export const swfDocumentSchema = z.object({
    document: z.object({
      dsl: z.string().optional(),
      namespace: z.string().optional(),
      name: z.string().optional(),
      version: z.string().optional(),
    }).optional(),
    input: z.unknown().optional(),
    output: z.unknown().optional(),
    do: z.array(z.record(z.unknown())),
    use: z.unknown().optional(),
    timeout: z.unknown().optional(),
    schedule: z.unknown().optional(),
  });
